project:
  type: website

website:
  title: "Digital nudging typology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



